### ISSUE TITLE
Remove dependency on cyhy module

### ISSUE THREAD

**Issue by dav3r** [cisagov/re-jira-import#4]
Currently, this code [imports the cyhy module](https://github.com/cisagov/re-jira-import/blob/master/rva_pusher2.py#L19), but it only uses it to [set up the database connection](https://github.com/cisagov/re-jira-import/blob/master/rva_pusher2.py#L157).

The `db_from_config()` function can easily be extracted and put in the `rva_pusher2.py` code, as was done by @KyleEvers in [this project](https://github.com/KyleEvers/dns_audit/blob/master/dns_audit.py#L122-L134).

This change will remove the [dependency on the currently-private cyhy-core](https://github.com/cisagov/re-jira-import/blob/master/requirements.txt#L1-L3) repository.

**Comment by jsf9k** [comment]
@dav3r, I think an even better solution might be to pull the `db_from_config()` code out into a small, public library.  That way all these other pieces of code could share the same functionality without having to pull in a private repo.  Furthermore, even if the repo were public, in many cases we don't really want to pull in all the dependencies of `cyhy-core` just to get `db_from_config()`.

What do you think?

**Comment by dav3r** [comment]
@jsf9k, that thought had crossed my mind.  I was thinking of a short-term fix since @kitaf004 had a need to run this code the other day, but didn't have access to the private cyhy repo.  However, I agree that a public repo for this (and potentially, other similar types of functions) is clearly a more elegant solution.

**Comment by jsf9k** [comment]
@felddy and I have already talked about the idea of having lots of small libraries instead of one giant behemoth called "util".

**Comment by dav3r** [comment]
Resolved by #5
